CREATE TABLE IF NOT EXISTS users (
    id BIGSERIAL PRIMARY KEY,
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(20) NOT NULL,
    CONSTRAINT password_length_check
    CHECK (LENGTH(password) >= 6)
    );

CREATE TABLE IF NOT EXISTS sites (
    id BIGSERIAL PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    url VARCHAR(2048) NOT NULL UNIQUE,
    code VARCHAR(50) NOT NULL UNIQUE,
    total INTEGER DEFAULT 0
    )