spring.liquibase.change-log=classpath:db/dbchangelog.xml
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/url-shortcut
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

url-shortcut.openapi.dev-url=http://localhost:8080
url-shortcut.openapi.prod-url=https://url-shortcut.com
url-shortcut.jwt.secret=local-development-secret-change-before-production

springdoc.swagger-ui.tryItOutEnabled=true

logging.level.org.springframework=ERROR
